topic_labels = {
        0: "İklim Değişikliği",
        1: "Enerji",
        2: "Biyoçeşitlilik",
        3: "Kirlilik",
        4: "Küresel Isınma",
        5: "Doğal Afetler",
        6: "Ormanlar ve Ağaçlandırma",
        7: "Su Kaynakları"
    }
single_action_suggestions = {
    "İklim Değişikliği": "İklim değişikliği ile mücadele için karbon salınımını azaltıcı çözümler üretin.",
    "Enerji": "Yenilenebilir enerji kullanımını artıran projeler geliştirerek enerji verimliliğini sağlayın.",
    "Biyoçeşitlilik": "Biyoçeşitliliği koruyan ve ekosistemleri sürdürülebilir hale getiren projeler geliştirin.",
    "Kirlilik": "Kirliliği azaltan yenilikçi teknolojiler ve atık yönetim çözümleri oluşturun.",
    "Küresel Isınma": "Küresel ısınmaya karşı bilinçlendirme kampanyaları düzenleyerek sürdürülebilir çözümler geliştirin.",
    "Doğal Afetler": "Doğal afet risklerini azaltan erken uyarı ve koruma sistemleri geliştirin.",
    "Ormanlar ve Ağaçlandırma": "Ormanları koruyarak, ağaçlandırma ve ormanlaştırma projelerine ağırlık verin.",
    "Su Kaynakları": "Su kaynaklarının sürdürülebilir kullanımını sağlayan ve su kirliliğini önleyen projeler geliştirin."
}

action_suggestions = {
    "Doğal Afetler, İklim Değişikliği": "İklim kaynaklı doğal afetlerin etkisini azaltacak erken uyarı sistemleri ve dayanıklılık projeleri tasarlayın.",
    "Doğal Afetler, Su Kaynakları": "Deprem, sel ve kuraklık gibi afetlerin etkilerini azaltmak için entegre su yönetimi planları oluşturun.",
    "Enerji, İklim Değişikliği": "Enerji üretiminde karbon nötr teknolojilere yönelerek iklim değişikliğiyle mücadele edin.",
    "Biyoçeşitlilik, İklim Değişikliği": "İklim değişikliğinin ekosistemler üzerindeki etkilerini azaltmak için biyoçeşitliliği koruyan adaptasyon projeleri oluşturun.",
    "İklim Değişikliği, Kirlilik": "Hava, su ve toprak kirliliğini azaltarak iklim değişikliği etkilerini sınırlandırmaya yönelik projeler geliştirin.",
    "Kirlilik, İklim Değişikliği": "Hava, su ve toprak kirliliğini azaltarak iklim değişikliği etkilerini sınırlandırmaya yönelik projeler geliştirin.",
    "İklim Değişikliği, Küresel Isınma": "Sera gazı salınımını azaltıcı politikalarla küresel ısınmanın hızını yavaşlatmaya odaklanın.",
    "Doğal Afetler, İklim Değişikliği": "İklim kaynaklı doğal afetlerin etkisini azaltacak erken uyarı sistemleri ve dayanıklılık projeleri tasarlayın.",
    "İklim Değişikliği, Ormanlar ve Ağaçlandırma": "Ağaçlandırma projeleri ve ormanların korunması yoluyla karbon tutulumunu artırarak iklim değişikliğiyle mücadele edin.",
    "Ormanlar ve Ağaçlandırma, İklim Değişikliği": "Ağaçlandırma projeleri ve ormanların korunması yoluyla karbon tutulumunu artırarak iklim değişikliğiyle mücadele edin.",
    "İklim Değişikliği, Su Kaynakları": "İklim değişikliğine dayanıklı su yönetimi projeleriyle su kaynaklarının sürdürülebilir kullanımını sağlayın.",
    "Su Kaynakları, İklim Değişikliği": "İklim değişikliğine dayanıklı su yönetimi projeleriyle su kaynaklarının sürdürülebilir kullanımını sağlayın.",
    "Biyoçeşitlilik, Enerji": "Enerji projelerinin biyoçeşitlilik üzerindeki olumsuz etkilerini azaltan çevre dostu çözümler üretin.",
    "Enerji, Kirlilik": "Temiz enerji kaynaklarını yaygınlaştırarak çevresel kirliliği azaltın ve enerji verimliliğini artırın.",
    "Enerji, Küresel Isınma": "Fosil yakıt kullanımını azaltan yenilenebilir enerji sistemlerini teşvik ederek küresel ısınmayı yavaşlatın.",
    "Doğal Afetler, Enerji": "Afet durumlarında enerji güvenliğini sağlayan yenilenebilir enerji altyapıları geliştirin.",
    "Enerji, Ormanlar ve Ağaçlandırma": "Biyokütle enerjisi gibi sürdürülebilir enerji yöntemlerini kullanarak orman ekosistemlerini destekleyin.",
    "Enerji, Su Kaynakları": "Su kaynaklarını koruyan ve su tüketimini minimize eden enerji üretim teknolojileri geliştirin.",
    "Biyoçeşitlilik, Kirlilik": "Ekosistemlerdeki kirliliği azaltmak için tür koruma ve habitat rehabilitasyon projeleri uygulayın.",
    "Biyoçeşitlilik, Küresel Isınma": "Biyoçeşitliliği küresel ısınma etkilerinden korumak için tür ve habitat odaklı koruma stratejileri geliştirin.",
    "Biyoçeşitlilik, Doğal Afetler": "Doğal afetlere karşı ekosistem direncini artırmak amacıyla biyoçeşitliliği güçlendirme çalışmaları yapın.",
    "Biyoçeşitlilik, Ormanlar ve Ağaçlandırma": "Doğal habitatların restorasyonu ve ormanlaştırma yoluyla biyolojik çeşitliliği artırıcı faaliyetlerde bulunun.",
    "Biyoçeşitlilik, Su Kaynakları": "Sulak alanları koruyarak su ekosistemlerinin biyolojik çeşitliliğini sürdürülebilir kılın.",
    "Kirlilik, Küresel Isınma": "Atık ve emisyon azaltıcı uygulamalarla kirlilik kaynaklı küresel ısınma etkilerini azaltın.",
    "Doğal Afetler, Kirlilik": "Afet sonrası ortaya çıkan çevresel kirliliği azaltmak için hızlı müdahale sistemleri geliştirin.",
    "Kirlilik, Ormanlar ve Ağaçlandırma": "Ormanları tehdit eden çevresel kirliliği azaltmak için sürdürülebilir atık yönetimi projeleri tasarlayın.",
    "Kirlilik, Su Kaynakları": "Su kirliliğini önlemek için atık su yönetimini geliştirin ve temiz su kaynaklarını koruyun.",
    "Doğal Afetler, Küresel Isınma": "Küresel ısınma kaynaklı afetlerin sıklığını ve etkilerini azaltacak politikalar geliştirin.",
    "Küresel Isınma, Ormanlar ve Ağaçlandırma": "Ormanlaştırma faaliyetlerini artırarak küresel ısınmaya karşı karbon yutakları oluşturun.",
    "Küresel Isınma, Su Kaynakları": "Su tasarrufu ve yönetimi politikalarıyla küresel ısınmanın su kaynakları üzerindeki etkilerini hafifletin.",
    "Doğal Afetler, Ormanlar ve Ağaçlandırma": "Doğal afetlere dirençli orman ekosistemleri geliştirmek için ekolojik restorasyon projeleri uygulayın.",
    "Ormanlar ve Ağaçlandırma, Su Kaynakları": "Su kaynaklarının sürdürülebilirliğini artırmak amacıyla ormanlaştırma ve ekosistem temelli su yönetimi projeleri geliştirin.",
    "İklim Değişikliği": "İklim değişikliği ile mücadele için karbon salınımını azaltıcı çözümler üretin.",
    "Enerji": "Yenilenebilir enerji kullanımını artıran projeler geliştirerek enerji verimliliğini sağlayın.",
    "Biyoçeşitlilik": "Biyoçeşitliliği koruyan ve ekosistemleri sürdürülebilir hale getiren projeler geliştirin.",
    "Kirlilik": "Kirliliği azaltan yenilikçi teknolojiler ve atık yönetim çözümleri oluşturun.",
    "Küresel Isınma": "Küresel ısınmaya karşı bilinçlendirme kampanyaları düzenleyerek sürdürülebilir çözümler geliştirin.",
    "Doğal Afetler": "Doğal afet risklerini azaltan erken uyarı ve koruma sistemleri geliştirin.",
    "Ormanlar ve Ağaçlandırma": "Ormanları koruyarak, ağaçlandırma ve ormanlaştırma projelerine ağırlık verin.",
    "Su Kaynakları": "Su kaynaklarının sürdürülebilir kullanımını sağlayan ve su kirliliğini önleyen projeler geliştirin."
}
topic_keywords = {
    "İklim Değişikliği": ["iklim", "iklim değişikliği", "sera gazı", "karbon", "emisyon", "küresel"],
    "Enerji": ["enerji", "güneş", "rüzgar", "yenilenebilir", "fosil", "elektrik", "nükleer", "petrol"],
    "Biyoçeşitlilik": ["biyoçeşitlilik", "canlı", "tür", "hayvan", "bitki", "yaban hayatı"],
    "Kirlilik": ["kirlilik", "hava kirliliği", "atık", "plastik", "kimyasal", "kirletici", "karbonmonoksit", "karbondioksit", "kömür", "nükleer"],
    "Küresel Isınma": ["küresel ısınma", "ısınma", "sıcaklık artışı", "sera etkisi", "sıcak", "kömür"],
    "Doğal Afetler": ["afet", "sel", "deprem", "kasırga", "heyelan", "yangın", "kurak", "enkaz", "don"],
    "Ormanlar ve Ağaçlandırma": ["orman", "ağaçlandırma", "ormanlık", "fidan", "yeşil alan", "ağaç"],
    "Su Kaynakları": ["su", "deniz", "okyanus", "dere", "akarsu", "nehir", "göl", "sulak", "kanal", "plaj", "buzul"]
}
